version: '3'

services:
  api:
    depends_on:
    - database #checks for mongo database container being started
    build: . #building this vs using the mongo docker
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      DATABASE_HOST: "tarpaulin" #
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    ports:
      - 8000:8000

  tarpaulin:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "hunter2"
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - 27017:27017 #map external port calls to internal port. ensures "going where we expect"